site_name: effector

nav:
  - Home: index.md
  - Install: installation.md
  - Quickstart: Tutorials/getting-started/tutorial_effector.md
  - Intro to Feature Effects:
    - Global Effects: global_effect_intro.md
    - Regional Effects: regional_effect_intro.md
  - Intro to Effector:
      - Use Effector with ML libraries: Tutorials/Guides/wrap_models.md
      - Methods Explained: tutorial_methods.md
  - Efficiency:
      - Global Effect: Tutorials/synthetic-examples/06_efficiency_global.md
      - Regional Effect: Tutorials/synthetic-examples/06_efficiency_regional.md
  - Synthetic Examples:
      - Conditional Interaction (1):
          - Global Effect: Tutorials/synthetic-examples/05_conditional_interaction_independent_uniform_global.md
          - Heterogeneity: Tutorials/synthetic-examples/05_conditional_interaction_independent_uniform_heter.md
          - Regional Effect: Tutorials/synthetic-examples/05_conditional_interaction_independent_uniform_regional.md
      - Conditional Interaction (2):
          - PDP: Tutorials/synthetic-examples/02_regional_pdp.md
          - RHALE: Tutorials/synthetic-examples/02_regional_rhale.md
          - SHAP-DP: Tutorials/synthetic-examples/02_regional_shapdp.md
  - Real Examples:
      - Bike Sharing: Tutorials/real-examples/01_bike_sharing_dataset.md
  - Extras:
      - Linear Model: Tutorials/synthetic-examples/01_linear_model.md
      - Comparing Global Effect Methods: Tutorials/synthetic-examples/02_global_effect_methods_comparison.md
      - Deep Dive into Regional Effects: Tutorials/synthetic-examples/03_regional_effects_synthetic_f.md
      - Regional Effect in depth (b): Tutorials/synthetic-examples/04_regional_effects_real_f.md
  - API: api.md
  - References: references.md


theme:
  name: material

  font:
    text: Roboto Flex
    code: Roboto Mono

  features:
    - navigation.footer
    - header.autohide
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [./../]
          rendering:
            show_source: true
            heading_level: 2

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - ../effector

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/givasile/effector
