name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*"

jobs:
  publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write  # Needed for OpenID Connect authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.EFFECTOR_GITHUB_API_KEY }}