name: Publish effector documentation to xai-effector/effector.github.io

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-build-docs.txt

    - name: Build docs
      run: |
        cd docs
        mkdocs build
        cd ..

    - name: Copy site to temp directory
      run: |
        mkdir ../site
        cp -r ./docs/site/* ../site
        cd ..

  copy-file:
    name: Copy site to effector.github.io
    needs:
    - build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: show cwd
      run: |
        pwd
        ls -la
        ls -la docs
        ls -la ./../
        ls -la ./../../

    - name: Push directory to effector.github.io
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.EFFECTOR_GITHUB_API_KEY }}
      with:
        source_folder: 'site'
        destination_repo: 'xai-effector/xai-effector.github.io'
        destination_branch: 'gh-pages'
        user_email: 'ntipakos@gmail.com'
        user_name: 'ntipakos'
        commit_msg: '[GHA] Update the test files.'


#    - name: Configure Git
#      run: |
#        git config --global user.email "ntipakos@github.com"
#        git config --global user.name "ntipakos"
#
#    - name: Commit and push to effector.github.io
#      run: |
#        git init
#        git add .
#        git commit -m "Update site from ntipakos/effector"
#        git push --force https://${{ secrets.EFFECTOR_GITHUB_API_KEY }}@github.com/xai-effector/effector.git gh-pages
